[package]
name = "metrics"
version = "0.0.2"
authors = ["Endre Karlson <endre.karlson@gmail.com>", "Alex Newman <posix4e@gmail.com>"]
description = "Coda Hale style metrics for rust"

documentation = "https://github.com/posix4e/rust-metrics/"
homepage = "https://github.com/posix4e/rust-metrics/"
repository = "https://github.com/posix4e/rust-metrics/"
readme = "README.md"
keywords = ["metrics", "graphite", "ganglia", "opentsdb"]
license = "Apache-2.0"

[dependencies]
time = "0.1.32"
num = "0.1.27"
histogram = "0.1.6"
log = "0.3.2"

[[test]]
name = "test"
path = "test/test.rs"
